### PR TITLE
Rough fix of @use rule usage

### PR DESCRIPTION
**Pull request by jan-rycko**
Allow to declare imports with `@use` rule in every file deduping its usage in merged file – hoisting it to the beginning. This fixes problem with this rule on my end. `dart-sass` warns about literal slash usage in favour of `math.div` and `list.slash` and I really wanted to use fast-sass-loader with it.

If you have better idea how to handle this – feel free to give me feedback.

### CODE REVIEW

**Comment by yibn2008** [comment]
@jan-rycko please merge the master and send the pull request again

**Comment by jan-rycko** [comment]
> @jan-rycko please merge the master and send the pull request again

@yibn2008 not sure how to `send pull request again` but I merged-in master so this pull request is up-to-date.

**Comment by yibn2008** [comment]
> > @jan-rycko please merge the master and send the pull request again
> 
> @yibn2008 not sure how to `send pull request again` but I merged-in master so this pull request is up-to-date.

never mind, it's ok now anyway, I just want to trigger the CI process :-)

**Comment by yibn2008** [comment]
new release: v2.0.1

**Pull request merged**
